spring:
  profiles: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    username: dgfopynwkbewax
    url: jdbc:postgresql://ec2-54-77-40-202.eu-west-1.compute.amazonaws.com:5432/dcitjum2ku0p1a
    password: 7670660450661ef15b6c6a2b93c2430ecb471e9475c73812e2a3c0b252134aef
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none
  mail:
    host: smtp.gmail.com
    port: 587
    username: hotcat.service@gmail.com
    password: wmwghunldfhoymug
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


management:
  endpoint:
    web:
      exposures:
        include: "*"

cors:
  allow-origin: "https://hotcat.vercel.app"

server:
  port: ${PORT}
  error:
    include-message: always

ACCESS_TOKEN_PRIVATE_KEY_PATH: "access-refresh-token-keys/access-token-private.key"
ACCESS_TOKEN_PUBLIC_KEY_PATH: "access-refresh-token-keys/access-token-public.key"
REFRESH_TOKEN_PRIVATE_KEY_PATH: "access-refresh-token-keys/refresh-token-private.key"
REFRESH_TOKEN_PUBLIC_KEY_PATH: "access-refresh-token-keys/refresh-token-public.key"