spring:
  profiles: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    username: diarbegisbayev
    url: jdbc:postgresql://localhost:5432/hotcat_db
    password: Reraha22
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: hotcat.service@gmail.com
    password: wmwghunldfhoymug
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


management:
  endpoint:
    web:
      exposures:
        include: "*"

cors:
  allow-origin: "https://hotcat.vercel.app"

server:
  port: 8080
  error:
    include-message: always




ACCESS_TOKEN_PRIVATE_KEY_PATH: "access-refresh-token-keys/access-token-private.key"
ACCESS_TOKEN_PUBLIC_KEY_PATH: "access-refresh-token-keys/access-token-public.key"
REFRESH_TOKEN_PRIVATE_KEY_PATH: "access-refresh-token-keys/refresh-token-private.key"
REFRESH_TOKEN_PUBLIC_KEY_PATH: "access-refresh-token-keys/refresh-token-public.key"